apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-http
  namespace: tenant-a
  labels:
    app: liveness-http
    cloud-env-minikube: supported
    cloud-env-bsc-aks: supported
    cloud-group: rest-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: liveness-http
  template:
    metadata:
      labels:
        app: liveness-http
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8088"
    spec:
      containers:
        - name: liveness
          image: bscanliksim/bsc-example-app-go:latest
          ports:
            - containerPort: 8088
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8088
            initialDelaySeconds: 3
            periodSeconds: 3
