apiVersion: v1
kind: Service
metadata:
  name: rest-qkt-service
  namespace: tenant-a
  labels:
    cloud-env-minikube: supported
    cloud-env-bsc-aks: supported
    cloud-group: rest
spec:
  selector:
    app: rest-qkt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort