apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    cloud-env-minikube: supported
    cloud-group: monitoring
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30005
  selector:
    name: grafana
  type: NodePort
