apiVersion: v1
kind: Service
metadata:
  name: prometheus-pushgateway
  namespace: monitoring
  labels:
    cloud-env-minikube: supported
    cloud-group: monitoring
spec:
  ports:
  - port: 9091
    protocol: TCP
    targetPort: 9091
    nodePort: 30007
  selector:
    name: prometheus-pushgateway
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-pushgateway
  namespace: monitoring
  labels:
    name: prometheus-pushgateway
    cloud-env-minikube: supported
    cloud-group: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus-pushgateway
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: prometheus-pushgateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
    spec:
      containers:
      - image: prom/pushgateway:v1.2.0
        imagePullPolicy: IfNotPresent
        name: prometheus-pushgateway
        ports:
          - containerPort: 9091
